apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
data:
  MYSQL_USER: bXl1c2Vy
  MYSQL_PASSWORD: bXlwYXNzd29yZA==
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==
