apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployments
  template:
    metadata:
      labels:
        app: nginx-deployments
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: "/"
            port: 80
        livenessProbe:
          httpGet:
            path: "/"
            port: 80
        resources:
          requests:
            memory: "256M"
            cpu: "100m"
          limits:
            memory: "512M"
            cpu: "1000m"
