apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-dep
  name: httpd-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-dep
  template:
    metadata:
      labels:
        app: httpd-dep
    spec:
      containers:
      - image: httpd
        name: httpd
